/** GET /protocol — the machine-readable protocol, generated from the registry. */
import { ANNOTATION_KINDS, CONFIDENCE_LEVELS, TOK_TYPE_MEANINGS, TOK_TYPES, KNOWLEDGE_SEMANTICS } from '../research/tok';
import { bootstrapDocument, bootstrapText, NOTICE } from './bootstrap';
import {
  DELEGABLE_SCOPES,
  INVARIANTS,
  INVARIANTS_V02,
  SUPPORTED_PROTOCOLS,
  PROTOCOL_NAME,
  PROTOCOL_TITLE,
  PROTOCOL_VERSION,
  RESOURCE_LIMITS,
  SCOPE_MEANINGS,
  VISIBILITY_MEANINGS,
} from './constants';
import { OPERATIONS, payloadJsonSchema, semanticsOf } from './operations';
import { PUBLISHED_SCHEMAS } from './schemas';
import { ERROR_STATUS } from './errors';

export function protocolDocument(base: string) {
  const u = (p: string) => new URL(p, base).toString();
  return {
    protocol: { name: PROTOCOL_NAME, version: PROTOCOL_VERSION, title: PROTOCOL_TITLE, spec: u('/protocol'), spec_json: u('/protocol.json') },
    type: 'protocol',
    notice: NOTICE,
    invariants: [...INVARIANTS],
    invariants_v02: [...INVARIANTS_V02],
    accepted_envelope_versions: [...SUPPORTED_PROTOCOLS],
    communication_model: {
      acsp: 'Actor → operation → state transition → persisted result → reference → independent actor → next operation.',
      not: 'Actor A → message → Actor B. ACSP carries no messages between sessions: sessions read and change persisted state, and pass references to it.',
      reference: 'A continuation reference (/r/{id}/continue/{operation_id}) identifies a persisted state. It carries no capability, no identity and no memory.',
    },
    summary:
      'ACSP is an HTTPS continuity substrate. A continuity resource at /r/{id} holds explicitly published research state (TOKs) ' +
      'with provenance. GET is always safe. Mutations are operations POSTed as a JSON envelope, authorised by capabilities.',
    concepts: {
      ownership: 'Exactly one owner session per resource; accountable; alone may update, delegate, revoke, resolve proposals, close.',
      access: VISIBILITY_MEANINGS,
      authority: 'Scopes carried by a capability (bearer token bound to one resource and one session).',
      delegation: 'The owner granting a named session scoped, expiring authority. Delegations cannot re-delegate.',
      task_responsibility: 'Per task TOK. Moves only by handoff (offer) + acknowledge (acceptance by the addressed session).',
      identity_assurance: {
        capability: 'The request presented a valid capability bound to the session_id.',
        asserted: 'No capability; the session_id is a claim. agent_id is always a claim.',
      },
      version: 'Increases by exactly 1 per event. A new resource is at version 1.',
      checkpoint: 'A numbered, hashed snapshot at one version. Checkpoint 0 is created with the resource. Distinct from version.',
      operation_intent: 'A described operation someone wants performed: prepared (GET ?action=prepare_<op>, never stored) or proposed (propose, stored).',
      operation: 'ACSP/0.2: one accepted mutation request, with a server-generated id (op-…). It produces one or more events and has an immutable record at /r/{id}/op/{operation_id}.',
      operational_state: 'ACSP/0.2: everything an operation can change (metadata, knowledge, handoffs, proposals, capability public fields, checkpoints). GET /r/{id}/state serves it with its SHA-256; each operation record carries the digest before and after.',
      lineage: 'ACSP/0.2: parent_operation_id (order, server), causation_id (the operation this one responds to: cited by the actor, or derived for resolve_proposal and acknowledge), correlation_id (workflow: supplied, inherited from causation, or the operation\'s own id).',
      extension: 'ACSP/0.2: a declarative operation registered by the service, composed only of core content operations; executable only in an executable status, only where the owner enabled it, only with authority covering every effect.',
    },
    scopes: SCOPE_MEANINGS,
    delegable_scopes: [...DELEGABLE_SCOPES],
    knowledge: {
      semantics: KNOWLEDGE_SEMANTICS,
      tok_types: TOK_TYPE_MEANINGS,
      tok_type_list: [...TOK_TYPES],
      stated_confidence: [...CONFIDENCE_LEVELS],
      statuses: ['active', 'superseded'],
      annotation_kinds: [...ANNOTATION_KINDS],
    },
    envelope: {
      method: 'POST',
      endpoint: '/r/{id}/operations (create: POST /r)',
      content_type: 'application/json (or an HTML form with fields request=<envelope JSON> and capability=<token>)',
      authentication: 'Authorization: Bearer <capability> or the envelope field "capability".',
      fields: {
        protocol: `Must be "${PROTOCOL_VERSION}".`,
        operation: 'A mutating operation name.',
        actor: '{ session_id, agent_id?, kind: agent|human|system }. With a capability, session_id must match it (or be omitted).',
        expected_version: 'The version you last inspected. Required for update, supersede, resolve_proposal, close.',
        idempotency_key: 'Required. 8-128 chars [A-Za-z0-9._:-]. Same key + same request = replay of the original response.',
        payload: 'Operation-specific; see operations[].payload_schema.',
        create_key: 'create only, when the operator requires it.',
        causation_id: 'ACSP/0.2, optional: an operation id of this resource (for fork: of the parent) that this operation responds to. Validated; grants nothing.',
        correlation_id: 'ACSP/0.2, optional: workflow id; inherited from causation_id when omitted.',
        operation_version: 'ACSP/0.2, optional: pin an extension definition version.',
      },
      response_v02: 'Adds operation_id, previous_version, operation_record (acsp.operation/0.2), continuation (acsp.continuation-reference/0.2), links.operation, links.continue and, when a secret was minted, secrets.paths. Every ACSP/0.1 field is unchanged.',
    },
    reading: {
      formats: 'Every GET is HTML by default; JSON via a .json suffix, ?format=json, or Accept: application/json.',
      credential: 'Optional ?cap=<capability> (capability URL — a secret) or Authorization: Bearer, to see your authority or read restricted resources.',
      endpoints: {
        '/r/{id}': 'inspect — canonical resource document',
        '/r/{id}?action=status': 'status',
        '/r/{id}?action=prepare_{op}': 'operation intent document + form (no side effects)',
        '/r/{id}/operations': 'operations and whether your credential permits each',
        '/r/{id}/events?after=N&limit=M': 'event history',
        '/r/{id}/events/{version}': 'one event',
        '/r/{id}/knowledge/{tokId}': 'one TOK',
        '/r/{id}/checkpoints': 'checkpoint list',
        '/r/{id}/checkpoints/{n}': 'one checkpoint with snapshot',
        '/r/{id}/diff?from=V&to=W | ?since_checkpoint=N': 'diff',
        '/r/{id}/explorer': 'protocol explorer (HTML, for developers)',
        '/r/{id}/op?after=S&limit=M&correlation_id=C': 'ACSP/0.2 operation records in sequence (poll with after=<sequence>)',
        '/r/{id}/op/{operation_id}': 'ACSP/0.2 one operation record with its lineage',
        '/r/{id}/continue[/{operation_id}]': 'ACSP/0.2 continuation reference, evaluated for YOUR authority',
        '/r/{id}/state': 'ACSP/0.2 current operational state and its SHA-256',
        '/r/{id}/proposals/{proposalId}': 'ACSP/0.2 a proposal as a protocol object (payload hash binding)',
        '/extensions[/{name}]': 'ACSP/0.2 extension operation registry',
        '/extensions/validate?definition=JSON': 'ACSP/0.2 validate a definition (never registers or executes it)',
        '/schemas[/{name}]': 'ACSP/0.2 JSON Schemas of the 0.2 documents',
      },
    },
    operations: OPERATIONS.map((o) => ({
      name: o.name,
      family: o.family,
      mutation: o.mutation,
      purpose: o.purpose,
      invocation: o.invocation,
      required_authority: o.authority,
      authority_text: o.authority_text,
      requires_expected_version: o.requires_expected_version,
      proposable: o.proposable,
      allowed_when_closed: o.allowed_when_closed,
      input: o.input,
      output: o.output,
      side_effects: o.side_effects,
      provenance: o.provenance,
      failures: o.failures,
      payload_schema: payloadJsonSchema(o),
      semantics: semanticsOf(o.name),
      doc_href: u(`/protocol#op-${o.name}`),
    })),
    errors: ERROR_STATUS,
    limits: RESOURCE_LIMITS,
    bootstrap: bootstrapDocument(),
    bootstrap_text: bootstrapText(),
    schemas: Object.keys(PUBLISHED_SCHEMAS).map((n) => ({ name: n, href: u(`/schemas/${n}`) })),
    links: { home: u('/'), new_resource: u('/new'), discovery: u('/.well-known/acsp'), extensions: u('/extensions'), schemas: u('/schemas') },
  };
}
export type ProtocolDocument = ReturnType<typeof protocolDocument>;
